version: '3'

services:
  jupyterlab:
    image: duke12321/jupyter_container:v1
    ports:
      - "8888:8888"
    working_dir: /home/jovyan/work
    volumes:
      - ./data_science:/home/jovyan/work
    user: "1000"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NOTEBOOK_DIR=/home/jovyan/work
    command: start-notebook.sh --NotebookApp.notebook_dir=/work
